services:
  # 本番環境のcontainerは https://github.com/s-hirano-ist/s-tools/blob/main/s-private/compose.yaml を参照

  dev_frontend:
    container_name: dev-frontend
    build:
      context: .
      dockerfile: docker/Dockerfile
    profiles:
      - dev
    ports:
      - "3000:3000"
    networks:
      - s-dev-network
    environment:
      - LINE_NOTIFY_URL=${LINE_NOTIFY_URL}
      - LINE_NOTIFY_SECRET_TOKEN=${LINE_NOTIFY_SECRET_TOKEN}
      - AUTH_URL=${AUTH_URL}
      - AUTH_SECRET=${AUTH_SECRET}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - NEXT_PUBLIC_G_TAG=${NEXT_PUBLIC_G_TAG}
      - POSTGRES_PRISMA_URL=${POSTGRES_PRISMA_URL}
      - POSTGRES_URL_NON_POOLING=${POSTGRES_URL_NON_POOLING}

  dev_db:
    container_name: dev-db
    build:
      context: .
      dockerfile: docker/db.Dockerfile
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - s-dev-network
    env_file:
      - .env

  dev_storage:
    container_name: dev-storage
    build:
      context: .
      dockerfile: docker/storage.Dockerfile
    ports:
      - "9000:9000"  # for access
      - "9001:9001"  # for console access
    volumes:
      - dev-storage-data:/data
      - ./minio/certs:/root/.minio/certs
    networks:
      - s-dev-network
    env_file:
      - .env

volumes:
  dev-db-data:
  dev-storage-data:

networks:
  s-dev-network:
    external: true
